services:
  msi-bot:
    image: nightmean/msi-reward-bot:latest
    container_name: msi_reward_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./screenshots:/app/screenshots
    environment:
      - DISCORD_WEBHOOK_URL=your_discord_webhook_url_here
      - DISCORD_USERNAME=MSI Rewards Daily Login Bot
      - MILESTONES=400,500,600
      - CRON_SCHEDULE=30 18 * * *
      - TZ=Europe/Bratislava
      - SAVE_SCREENSHOTS=false
